name: Push Release to PyPi

on:
  workflow_dispatch:

jobs:
  run_tests:
    uses: ./.github/workflows/run_tests.yaml
    secrets: inherit

  upload_to_pypi:
    needs: run_tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Setup conda env
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          activate-environment: test
          python-version: 3.8
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          set -eux
          conda activate test
          conda install pytorch cpuonly -c pytorch-nightly
          pip install -r requirements.txt
          pip install -r dev-requirements.txt
          pip install --no-build-isolation -e ".[dev]"
      - name: Upload to PyPI
        shell: bash -l {0}
        env:
          PYPI_USER: ${{ secrets.PYPI_USER_RELEASE }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN_RELEASE }}
        run: |
          set -eux
          conda activate test
          pip install twine
          python setup.py sdist bdist_wheel
          twine upload --username "$PYPI_USER" --password "$PYPI_TOKEN" dist/* --verbose
